# Generated by Django 3.0.7 on 2020-06-19 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200619_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='discussion',
        ),
        migrations.AddField(
            model_name='discussiontext',
            name='filename',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Document'),
        ),
    ]
