# Generated by Django 3.0.7 on 2020-06-19 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200619_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussiontext',
            old_name='filename',
            new_name='document',
        ),
    ]
