# Generated by Django 3.0.7 on 2020-06-19 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200619_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='files_to_contrib',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='web.Document'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personal_files',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='web.Document'),
        ),
    ]
