# Generated by Django 3.0.7 on 2020-06-19 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200619_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='users',
        ),
    ]
