# Generated by Django 3.0.7 on 2020-06-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_remove_document_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='files_to_contrib',
        ),
        migrations.AddField(
            model_name='profile',
            name='files_to_contrib',
            field=models.ManyToManyField(related_name='reviewer', to='web.Document'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='personal_files',
        ),
        migrations.AddField(
            model_name='profile',
            name='personal_files',
            field=models.ManyToManyField(related_name='owner', to='web.Document'),
        ),
    ]
