# Generated by Django 3.0.7 on 2020-06-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20200619_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='agreed_files',
            field=models.ManyToManyField(related_name='agreed', to='web.Document'),
        ),
        migrations.AddField(
            model_name='profile',
            name='canceled_files',
            field=models.ManyToManyField(related_name='canceled', to='web.Document'),
        ),
    ]
