# Generated by Django 3.0.7 on 2020-06-19 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20200619_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='agreed_files',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='canceled_files',
        ),
    ]
