# Generated by Django 3.0.7 on 2020-06-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20200619_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='signs_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
