# Generated by Django 3.0.7 on 2020-06-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_document_signs_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(default='In progress', max_length=25),
        ),
    ]
