# Generated by Django 3.0.7 on 2020-06-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_document_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='signed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
