# Generated by Django 3.0.3 on 2020-07-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_document_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='filepath',
            field=models.FilePathField(null=True, path='C:\\Python projects\\dokumentooborot\\media'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(default='В процессе', max_length=25),
        ),
    ]
