# Generated by Django 3.0.3 on 2020-07-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_document_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='filepath',
            field=models.FilePathField(null=True, path='C:\\Python projects\\dokumentooborot\\media'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(default='В процессе', max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='files_to_contrib',
            field=models.ManyToManyField(blank=True, related_name='reviewer', to='web.Document'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notifications',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personal_files',
            field=models.ManyToManyField(blank=True, related_name='owner', to='web.Document'),
        ),
    ]
