# Generated by Django 3.0.3 on 2020-07-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20200704_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='files_to_contrib',
            field=models.ManyToManyField(blank=True, null=True, related_name='reviewer', to='web.Document'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personal_files',
            field=models.ManyToManyField(blank=True, null=True, related_name='owner', to='web.Document'),
        ),
    ]
